name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: "::error::This is an error"
      - run: "::warning::This is a warning"
      - run: "::notice::This is a notice"